version: '3.7'

networks:
  net:    
   driver: overlay

services:
  mysql:
    image: mysql:5.7.31
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./conf/mysql/scripts:/docker-entrypoint-initdb.d
      - ./conf/mysql/conf/my.cnf:/etc/mysql/my.cnf
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    command: [--ssl=0]
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    extra_hosts:
      - "wso2.local:192.168.0.88"
    networks:
      - net    
  am-analytics-worker:
    build: ./dockerfiles/apim-analytics-worker
    ports:
      - "9091"
      - "9444"
    healthcheck:
      test: ["CMD", "nc", "-z","localhost", "9444"]
      interval: 10s
      start_period: 20s
      retries: 5
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./conf/apim-analytics-worker:/home/wso2carbon/wso2-config-volume
    extra_hosts:
      - "wso2.local:192.168.0.88"
    networks:
      - net  
  api-manager:
    build: ./dockerfiles/apim
    volumes:
      - ./conf/apim:/home/wso2carbon/wso2-config-volume
    ports:
      - "9443:9443"
      - "8280:8280"
      - "8243:8243"
    extra_hosts:
      - "wso2.local:192.168.0.88"
    networks:
      - net   
  api-manager-hm:
    build: ./dockerfiles/apim
    volumes:
      - ./conf/apim-hm:/home/wso2carbon/wso2-config-volume
    ports:
      - "9444:9444"
      - "8281:8281"
      - "8244:8244"
    extra_hosts:
      - "wso2.local:192.168.0.88"
    networks:
      - net
  api-manager-ds:
    build: ./dockerfiles/apim
    volumes:
      - ./conf/apim-ds:/home/wso2carbon/wso2-config-volume
    ports:
      - "9445:9445"
      - "8282:8282"
      - "8245:8245"
    extra_hosts:
      - "wso2.local:192.168.0.88"
    networks:
      - net 
  am-analytics-dashboard:
    build: ./dockerfiles/apim-analytics-dashboard
    ports:
      - "9643:9643"
    healthcheck:
      test: ["CMD", "nc", "-z","localhost", "9643"]
      interval: 10s
      retries: 5
      start_period: 20s
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./conf/apim-analytics-dashboard:/home/wso2carbon/wso2-config-volume
    extra_hosts:
      - "wso2.local:192.168.0.88"
    networks:
      - net
